version: '3'

services:
  cara:
    build: ../masuda-app-cara
    image: cara:1
    networks:
      - frontend

  coroa:
    build: ../masuda-app-coroa
    image: coroa:1
    networks:
      - frontend

  balancer:
    image: ikauzak/masuda-app:1.1
    networks:
      - frontend
      - backend
    ports:
      - 80:80
    depends_on:
      - cara
      - coroa

networks:
  frontend:
  backend:
